import { useState, useEffect, useCallback } from 'react';
import { Bell, Filter, RefreshCw, Wifi, WifiOff, CheckCircle, Search as SearchIcon } from 'lucide-react';
import { getAlerts, updateAlertStatus } from '../api';
import useWebSocket from '../hooks/useWebSocket';

const SEV_ORDER = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };

export default function Alerts() {
    const [alerts, setAlerts] = useState([]);
    const [total, setTotal] = useState(0);
    const [loading, setLoading] = useState(true);
    const [sevFilter, setSevFilter] = useState('');
    const [statusFilter, setStatusFilter] = useState('');
    const [newAlertIds, setNewAlertIds] = useState(new Set());

    const fetchAlerts = useCallback(async () => {
        try {
            const data = await getAlerts(sevFilter || undefined, statusFilter || undefined);
            setAlerts(data.items || []);
            setTotal(data.total || 0);
        } catch (e) { /* ignore */ }
        setLoading(false);
    }, [sevFilter, statusFilter]);

    useEffect(() => { fetchAlerts(); }, [fetchAlerts]);

    // ── WebSocket for live updates ───────────────────────────────────────
    const handleWsMessage = useCallback((msg) => {
        if (msg.type === 'new_alert') {
            const alert = msg.data;
            setAlerts(prev => [alert, ...prev]);
            setTotal(prev => prev + 1);
            // Highlight new alert briefly
            setNewAlertIds(prev => new Set(prev).add(alert.id));
            setTimeout(() => {
                setNewAlertIds(prev => {
                    const next = new Set(prev);
                    next.delete(alert.id);
                    return next;
                });
            }, 3000);
        }
    }, []);

    const { isConnected } = useWebSocket('ws://localhost:8000/ws/alerts', {
        onMessage: handleWsMessage,
    });

    // ── Alert status management ──────────────────────────────────────────
    const handleStatusChange = async (alertId, newStatus) => {
        try {
            await updateAlertStatus(alertId, newStatus);
            setAlerts(prev =>
                prev.map(a => a.id === alertId ? { ...a, status: newStatus } : a)
            );
        } catch (e) {
            console.error('Failed to update status:', e);
        }
    };

    const sorted = [...alerts].sort((a, b) =>
        (SEV_ORDER[a.severity] ?? 5) - (SEV_ORDER[b.severity] ?? 5)
    );

    return (
        <div>
            <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                    <h2>🔔 Alerts</h2>
                    <p>Security alerts generated by the detection engine</p>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.8rem' }}>
                    {isConnected ? (
                        <><Wifi size={14} style={{ color: 'var(--success)' }} /><span style={{ color: 'var(--success)' }}>Live</span></>
                    ) : (
                        <><WifiOff size={14} style={{ color: 'var(--text-dim)' }} /><span style={{ color: 'var(--text-dim)' }}>Offline</span></>
                    )}
                </div>
            </div>

            {/* Filters */}
            <div className="card" style={{ marginBottom: '1rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', flexWrap: 'wrap' }}>
                    <Filter size={16} style={{ color: 'var(--text-dim)' }} />
                    <select className="form-select" value={sevFilter} onChange={e => setSevFilter(e.target.value)}>
                        <option value="">All Severities</option>
                        <option value="critical">Critical</option>
                        <option value="high">High</option>
                        <option value="medium">Medium</option>
                        <option value="low">Low</option>
                    </select>
                    <select className="form-select" value={statusFilter} onChange={e => setStatusFilter(e.target.value)}>
                        <option value="">All Status</option>
                        <option value="new">New</option>
                        <option value="investigating">Investigating</option>
                        <option value="resolved">Resolved</option>
                        <option value="false_positive">False Positive</option>
                    </select>
                    <div style={{ flex: 1 }} />
                    <span style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>{total} alerts</span>
                    <button className="btn btn-secondary" onClick={fetchAlerts} style={{ fontSize: '0.8rem' }}>
                        <RefreshCw size={14} /> Refresh
                    </button>
                </div>
            </div>

            {/* Table */}
            {loading ? (
                <div className="loading-state"><div className="loading-spinner" /><p>Loading alerts...</p></div>
            ) : sorted.length === 0 ? (
                <div className="card empty-state"><p>No alerts matching filters</p></div>
            ) : (
                <div className="card" style={{ overflowX: 'auto' }}>
                    <table className="data-table">
                        <thead>
                            <tr>
                                <th>SEVERITY</th>
                                <th>TITLE</th>
                                <th>TYPE</th>
                                <th>SOURCE IP</th>
                                <th>MITRE TECHNIQUES</th>
                                <th>STATUS</th>
                                <th>ACTIONS</th>
                            </tr>
                        </thead>
                        <tbody>
                            {sorted.map(alert => (
                                <tr key={alert.id}
                                    className={`animate-in ${newAlertIds.has(alert.id) ? 'new-alert-flash' : ''}`}
                                    style={newAlertIds.has(alert.id) ? {
                                        background: 'rgba(249,115,22,0.08)',
                                        transition: 'background 0.5s ease',
                                    } : {}}>
                                    <td>
                                        <span className={`severity-badge severity-${alert.severity}`}>
                                            {alert.severity.toUpperCase()}
                                        </span>
                                    </td>
                                    <td>
                                        <div style={{ fontWeight: 600, fontSize: '0.85rem' }}>{alert.title}</div>
                                        <div style={{ fontSize: '0.75rem', color: 'var(--text-dim)', maxWidth: 300, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                                            {alert.description}
                                        </div>
                                    </td>
                                    <td><span className="tag">{alert.detection_type}</span></td>
                                    <td>
                                        <span className="mono" style={{ fontSize: '0.82rem' }}>
                                            {alert.source_ip || '—'}
                                        </span>
                                    </td>
                                    <td>
                                        <div style={{ display: 'flex', gap: '0.3rem', flexWrap: 'wrap' }}>
                                            {(alert.mitre_technique_ids || []).map(t => (
                                                <span key={t} className="tag">{t}</span>
                                            ))}
                                        </div>
                                    </td>
                                    <td>
                                        <span style={{
                                            fontSize: '0.75rem', fontWeight: 700, textTransform: 'uppercase',
                                            color: alert.status === 'new' ? 'var(--success)' :
                                                alert.status === 'investigating' ? '#eab308' :
                                                    alert.status === 'resolved' ? 'var(--text-dim)' : 'var(--text-secondary)',
                                        }}>
                                            {alert.status.replace('_', ' ')}
                                        </span>
                                    </td>
                                    <td>
                                        {alert.status === 'new' && (
                                            <button className="btn btn-secondary"
                                                style={{ fontSize: '0.7rem', padding: '0.2rem 0.5rem' }}
                                                onClick={() => handleStatusChange(alert.id, 'investigating')}>
                                                Investigate
                                            </button>
                                        )}
                                        {alert.status === 'investigating' && (
                                            <button className="btn btn-secondary"
                                                style={{ fontSize: '0.7rem', padding: '0.2rem 0.5rem' }}
                                                onClick={() => handleStatusChange(alert.id, 'resolved')}>
                                                <CheckCircle size={12} /> Resolve
                                            </button>
                                        )}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}
