import { useState, useEffect } from 'react';
import { Filter, RefreshCw } from 'lucide-react';
import { fetchAlerts } from '../api';

export default function Alerts() {
    const [alerts, setAlerts] = useState([]);
    const [total, setTotal] = useState(0);
    const [loading, setLoading] = useState(true);
    const [severityFilter, setSeverityFilter] = useState('');
    const [statusFilter, setStatusFilter] = useState('');

    const load = () => {
        setLoading(true);
        fetchAlerts(severityFilter || null, statusFilter || null)
            .then(data => {
                setAlerts(data.items || []);
                setTotal(data.total || 0);
                setLoading(false);
            })
            .catch(() => setLoading(false));
    };

    useEffect(() => { load(); }, [severityFilter, statusFilter]);

    return (
        <div>
            <div className="page-header">
                <h2>🔔 Alerts</h2>
                <p>Security alerts generated by the detection engine</p>
            </div>

            {/* Filters */}
            <div className="card" style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' }}>
                <Filter size={16} style={{ color: 'var(--text-dim)' }} />
                <div>
                    <select className="form-select" style={{ width: 'auto', minWidth: 140 }}
                        value={severityFilter} onChange={e => setSeverityFilter(e.target.value)}>
                        <option value="">All Severities</option>
                        <option value="critical">Critical</option>
                        <option value="high">High</option>
                        <option value="medium">Medium</option>
                        <option value="low">Low</option>
                        <option value="info">Info</option>
                    </select>
                </div>
                <div>
                    <select className="form-select" style={{ width: 'auto', minWidth: 140 }}
                        value={statusFilter} onChange={e => setStatusFilter(e.target.value)}>
                        <option value="">All Status</option>
                        <option value="new">New</option>
                        <option value="acknowledged">Acknowledged</option>
                        <option value="resolved">Resolved</option>
                    </select>
                </div>
                <div style={{ marginLeft: 'auto', color: 'var(--text-dim)', fontSize: '0.8rem' }}>
                    {total} alert{total !== 1 ? 's' : ''}
                </div>
                <button className="btn btn-secondary btn-sm" onClick={load}>
                    <RefreshCw size={14} /> Refresh
                </button>
            </div>

            {/* Table */}
            <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
                {loading ? (
                    <div className="loading-state"><div className="loading-spinner" /><p>Loading alerts...</p></div>
                ) : alerts.length === 0 ? (
                    <div className="empty-state" style={{ padding: '3rem' }}>
                        <p>No alerts found. Ingest some logs to generate alerts.</p>
                    </div>
                ) : (
                    <div style={{ overflowX: 'auto' }}>
                        <table className="data-table">
                            <thead>
                                <tr>
                                    <th>Severity</th>
                                    <th>Title</th>
                                    <th>Type</th>
                                    <th>Source IP</th>
                                    <th>MITRE Techniques</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {alerts.map((alert, idx) => (
                                    <tr key={idx} className="animate-in" style={{ animationDelay: `${idx * 0.02}s` }}>
                                        <td>
                                            <span className={`severity-badge severity-${alert.severity}`}>
                                                {alert.severity}
                                            </span>
                                        </td>
                                        <td>
                                            <div style={{ fontWeight: 600, fontSize: '0.85rem' }}>{alert.title}</div>
                                            <div style={{ fontSize: '0.73rem', color: 'var(--text-dim)', maxWidth: 350, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                                                {alert.description}
                                            </div>
                                        </td>
                                        <td>
                                            <span className="tag">{alert.detection_type || 'rule'}</span>
                                        </td>
                                        <td className="mono">{alert.source_ip || '—'}</td>
                                        <td>
                                            <div style={{ display: 'flex', gap: '0.3rem', flexWrap: 'wrap' }}>
                                                {(alert.mitre_technique_ids || []).slice(0, 3).map((t, i) => (
                                                    <span key={i} className="tag">{t}</span>
                                                ))}
                                            </div>
                                        </td>
                                        <td>
                                            <span style={{
                                                fontSize: '0.72rem', fontWeight: 600, textTransform: 'uppercase',
                                                color: alert.status === 'new' ? 'var(--critical)' : 'var(--success)',
                                            }}>
                                                {alert.status}
                                            </span>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>
        </div>
    );
}
