"""Alert model — generated when detection rules or anomalies fire."""

from __future__ import annotations

from typing import Any
from uuid import UUID

from sqlalchemy import JSON
from sqlmodel import Column, Field, SQLModel

from threattriage.models.base import AlertStatus, Severity, TimestampMixin, generate_uuid


class Alert(TimestampMixin, SQLModel, table=True):
    """A security alert generated by the detection or anomaly engine."""

    __tablename__ = "alerts"

    id: UUID = Field(default_factory=generate_uuid, primary_key=True)

    # ── Core ──────────────────────────────────────────────────────────────
    title: str = Field(description="Human-readable alert title")
    description: str = Field(description="Detailed description of what was detected")
    severity: Severity = Field(index=True)
    status: AlertStatus = Field(default=AlertStatus.NEW, index=True)
    confidence: float = Field(
        default=0.5, ge=0.0, le=1.0,
        description="Confidence score (0.0–1.0)",
    )

    # ── Detection Source ──────────────────────────────────────────────────
    rule_id: str | None = Field(default=None, index=True, description="Detection rule that triggered this")
    rule_name: str | None = Field(default=None)
    detection_type: str = Field(default="rule", description="rule | anomaly | correlation")

    # ── Context ──────────────────────────────────────────────────────────
    source_ip: str | None = Field(default=None, index=True)
    destination_ip: str | None = Field(default=None)
    hostname: str | None = Field(default=None)
    username: str | None = Field(default=None)

    # ── IOC References ────────────────────────────────────────────────────
    ioc_values: list[str] | None = Field(
        default=None,
        sa_column=Column(JSON, nullable=True),
        description="IOC values associated with this alert",
    )

    # ── MITRE ATT&CK ─────────────────────────────────────────────────────
    mitre_technique_ids: list[str] | None = Field(
        default=None,
        sa_column=Column(JSON, nullable=True),
        description="MITRE ATT&CK technique IDs (e.g., T1110.001)",
    )
    mitre_tactic: str | None = Field(default=None, description="Primary MITRE tactic")

    # ── Related Logs ─────────────────────────────────────────────────────
    log_entry_ids: list[str] | None = Field(
        default=None,
        sa_column=Column(JSON, nullable=True),
        description="UUIDs of log entries that triggered this alert",
    )
    log_count: int = Field(default=1, description="Number of log entries involved")

    # ── Incident Reference ────────────────────────────────────────────────
    incident_id: UUID | None = Field(default=None, foreign_key="incidents.id", index=True)

    # ── Enrichment Summary ────────────────────────────────────────────────
    enrichment_data: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(JSON, nullable=True),
        description="TI enrichment summary for quick access",
    )

    # ── Analyst Notes ─────────────────────────────────────────────────────
    analyst_notes: str | None = Field(default=None)
